### ISSUE TITLE
[ENH] QRCode 생성시 deviceId, adminId, totp로 생성

### ISSUE THREAD

**Issue by riyenas0925** [osamhack2020/APP_KookMoBanUser_PonJohmNaimann#7]
@Jinwhuy  기존 방식에서 adminId만 추가해주시면 됩니다~

* QRcode를 deviceId, adminId, 생성된 totp 값으로만 생성

**Comment by Jinwhuy** [comment]
@riyenas0925 
QRcode 생성시 deviceID, adminID, TOTP 값 순서대로 하나의 String으로 만들어서 QR코드를 만들면 되나요?

**Comment by riyenas0925** [comment]
@Jinwhuy  저는 해시맵에 담고 json으로 변환한다음 string으로 변경했습니다!

```
Map<String, Object> params = new HashMap<String, Object>();
params.put("deviceId", deviceId);
params.put("adminId", adminId);
params.put("totp", totp);

ObjectMapper mapper = new ObjectMapper();
String jsonStr = mapper.writeValueAsString(params);
```

**Comment by riyenas0925** [comment]
RAW TEXT 부분 처럼 String으로 변환된 json으로 보내지면 됩니다~
![Untitled](https://user-images.githubusercontent.com/32615702/96233878-a2df6e80-0fd3-11eb-9973-480bd7c36e28.png)

**Comment by Jinwhuy** [comment]
@riyenas0925 
제가 kotlin으로 작업을 해서요~ 아래처럼 코딩했는데 한번 확인 부탁드립니다!
파란색 부분으로 음영넣은 부분이 QR코드 생성시 코드를 넣는 부분입니다.

![image](https://user-images.githubusercontent.com/71877784/96243742-1dae8680-0fe0-11eb-9379-61be18a08246.png)

**Comment by riyenas0925** [comment]
넵넵 코드상으로는 맞는것 같습니다~ 그래도 혹시 모르니까 아래 사이트에서 한번 디코딩 해보시겠어요?
https://zxing.org/w/decode.jspx

**Comment by Jinwhuy** [comment]
@riyenas0925 사지방에서 애뮬레이터 동작이 안되서요. 우선 close 안하고 커밋한 다음, 오류가 발생하면 수정하겠습니다.

**Comment by riyenas0925** [comment]
@Jinwhuy 넵넵~ 제가 테스트 해드리면 될까요?
